---
server:
    install: '1'
    packages: [vim, git]
    timezone: America/Sao_Paulo
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty32, hostname: phpapi, ip: 192.168.33.33, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mysql:
    install: '1'
    root_password: root
    database: apigility_ionic_ok
    user: root
    password: senha
    dump: apigility_ionic_ok.sql
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-common, php5-fpm, php5-mysql]

